Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [1]:
import numpy as np 
A = np.arange(1, 16).reshape(3,5)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype) 



2
(3, 5)
15
int32


Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [3]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)


subtraction = B - C 
multiplication = B * C 
matrix_multiplication = B @ C 

print(subtraction)
print(multiplication)
print(matrix_multiplication)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [3]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()

exp = np.exp(B)
print(exp)
print()

B_min = B.min
print(B_min)
print()

B_min_row = B.min(axis = 1)
print(B_min_row)
print()

B_min_c = B.min(axis = 0)
print(B_min_c)
print()

min_value = np.argmin(B)
print(min_value)
print()

min_value_row = np.argmin(B, axis = 1)
print(min_value_row)
print()

sum = B.sum
print(sum)
print()

mean = B.mean(axis = 0)
print(mean)
print()

median = np.median(B,axis = 0)
print(median)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

<built-in method min of numpy.ndarray object at 0x000002328F65B9F0>

[1 4 7]

[1 2 3]

0

[0 0 0]

<built-in method sum of numpy.ndarray object at 0x000002328F65B9F0>

[4. 5. 6.]

[4. 5. 6.]


What does it mean when you provide fewer indices than axes when slicing? See example below.

print(A)
A[1]


Svar: 
när man anger färre index än antalet rader i matrisen resulterar det i att man väljer en rad i matrisen samt att dimensionen på matrisen minskas till det index som angavs. 

In [10]:
print(A)
A[1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([ 6,  7,  8,  9, 10])

In [9]:
A
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


Förklara vad koden gör och vad innebär det att b har 3 axlar 

#skapar en matris a med värden 0-29 i en rad
a = np.arange(30)

#omvandlar matris a till en 3 dimensionerad matris b, där numpy räknar ut dimensionen automatiskt
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [11]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Broadcasting

#en matris m1 skapas med 
m1 = np.array([[1, 2], [3, 4]])

#en matris m2 skapas 
m2 = np.array([1, 1])

#när m1 och m2 adderas kommer m1 att strechas för att matcha m1:s dimension, när dimensionerna stämmer kommer m1 och m2 adders, dvs m2 kommer bli en matris som ser ut som följande [1, 1], [1, 1]
print(m1 + m2)

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

v1 = np.array([1, 2, 3])
print(v1 + 1)
#denna addition funkar för att broadcasting kommer addera 1 till varje summa i v1

A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

#Om A + b skulle adderas hade detta med funkar då b hade strechat och blivit en matris med [2, 2], [2, 2] och därefter hade additionen genomförts. 

In [13]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [15]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [16]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [17]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Svar: när v2 skrivs som ovan kommer en view att skapas av v1. Efersom v2[-1] ändrar sista elementet i v2 kommer därför även v1 att ändras

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

def add_mult_matrices(M1, M2, add_or_multi):
    if not isinstance(M1, np.ndarray) or not isinstance(M2, np.ndarray):
        raise Error("M1 och M2 måste vara numpy.ndarray)
    if add_or_multi not in ["add", "multi"]:
        raise Error("Måste vara add eller multi)
    if add_or_multi == "add":
        if M1.shape != M2.shape:
            raise Error("matriser måste ha samma dimension)
        return M1 + M2
    else: 
        return M1 @ M2


Uppgift 10.1.1. Definiera vektorn x enligt nedan.
x = (4, 3)
(a) Vilken dimension har vektorn x?
(b) Ber¨akna 5x.
(c) Ber¨akna 3x.
(d) Ber¨akna 5x + 3x.
(e) Ber¨akna 8x.
(f) Ber¨akna 4x − x.
(g) Ber¨akna x
⊤, vilken blir den nya dimensionen efter att
transponeringen utf¨orts?
(h) Ar ¨ x + x
⊤ definierat?
(i) Ber¨akna ∥x∥.

In [7]:
import numpy as np


In [45]:
x = np.array([4, 3])
print(x)
print(x.shape)
print()

print(5*x)
print()

print(3*x)
print()

print(5*x+3*x)
print()

print(8*x)
print()

print(4*x - x)
print()

print(x.T)
print()
print()

print(x.T)
x_T_shape = x.T.shape
print(x_T_shape)
print()

print(np.linalg.norm(x))

[4 3]
(2,)

[20 15]

[12  9]

[32 24]

[32 24]

[12  9]

[4 3]


[4 3]
(2,)

5.0


Uppgift 10.1.2. Definiera vektorn v enligt nedan.
v =
(
3
7
0
11)
(a) Vilken dimension har vektorn v?
(b) Ber¨akna 2v.
380
(c) Ber¨akna 5v + 2v.
(d) Ber¨akna 4v − 2v.
(e) Ber¨akna v
⊤, vilken blir den nya dimensionen efter att
transponeringen utf¨orts?
(f) Ber¨akna ∥v∥

In [48]:
v = np.array([3, 7, 0, 11])

print(v.shape)
print()

print(2*v)
print()

print(5*v + 2*v)
print()

print(4*v - 2*v)
print()

print(v.T)
v_T_shape = v.T.shape
print(v_T_shape)
print()

print(np.linalg.norm(v))




(4,)

[ 6 14  0 22]

[21 49  0 77]

[ 6 14  0 22]

[ 3  7  0 11]
(4,)

13.379088160259652


10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och
v2 = (2, 3, 1, 1).
(a) Ber¨akna ∥v1∥.
(b) Ber¨akna ∥v1 − v2∥.

In [50]:
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

print(np.linalg.norm(v1))
print()

print(np.linalg.norm(v1-v2))

7.14142842854285

4.47213595499958


Uppgift 10.2.1


In [58]:
A = np.array([[2, 1, -1,], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([1, 2])
I = np.array([[1, 0], [0, 1]])
print(I)

[[1 0]
 [0 1]]


In [63]:
print(2*A)
print()

print(B-2*A)
print()


[[ 4  2 -2]
 [ 2 -2  2]]

[[ 0 -4  3]
 [ 0 -2 -4]]



In [76]:
def add_mult_matrices(M1, M2, add_or_multi):
    if not isinstance(M1, np.ndarray) or not isinstance(M2, np.ndarray):
        raise ValueError("M1 och M2 måste vara numpy.ndarray")
    if add_or_multi not in ["add", "multi"]:
        raise ValueError("Måste vara add eller multi")
    if add_or_multi == "add":
        if M1.shape != M2.shape:
            raise ValueError("matriser måste ha samma dimension")
        return M1 + M2
    else: 
        return M1 @ M2

In [91]:

C = np.array([[1, 2], [2, 1]])
E = np.array([1, 2])

try:
    resultat = add_mult_matrices(2*C, -2*E, "add")
    print(resultat)
except ValueError as fel:
    print(fel)



matriser måste ha samma dimension


In [92]:
try:
    resultat = add_mult_matrices(2*D, -3*C, "add")
    print(resultat)
except ValueError as fel:
    print(fel)

[[3 2]
 [2 3]]


In [93]:
try:
    resultat = add_mult_matrices(D.T, 2*D, "add")
    print(resultat)
except ValueError as fel:
    print(fel)

Resultat av addition: [[ 9 12]
 [12  9]]


In [95]:
try:
    resultat = add_mult_matrices(2*C.T, -2*D.T, "add")
    print(resultat)
except ValueError as fel:
    print(fel)

[[-4 -4]
 [-4 -4]]


In [102]:
try:
    resultat = add_mult_matrices(A.T, -B, "add")
    print(resultat)
except ValueError as fel:
    print(fel)

matriser måste ha samma dimension


In [103]:
try:
    resultat = add_mult_matrices(A, C, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


In [104]:
try:
    resultat = add_mult_matrices(C, D, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[11 10]
 [10 11]]


In [106]:
try:
    resultat = add_mult_matrices(C, B, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[  8 -10  -3]
 [ 10  -8   0]]


In [107]:
try:
    resultat = add_mult_matrices(C, I, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[1 2]
 [2 1]]


In [109]:
try:
    resultat = add_mult_matrices(A, B.T, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[5 2]
 [7 4]]


10.2.2

In [111]:
A = np.array([[2, 3, 4], [5, 4, 1]])

try:
    resultat = add_mult_matrices(A, A.T, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[29 26]
 [26 42]]


10.2.3

In [119]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

try:
    resultat = add_mult_matrices(A, B, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)
print()
try:
    resultat = add_mult_matrices(A, C, "multi")
    print(resultat)
except ValueError as fel:
    print(fel)

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]
